- hosts: localhost
  tasks:
  - name: Install packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
    become: true
    vars:
      packages:
      - git

  - import_tasks: zsh.yml 

  - import_tasks: dotfiles.yml 

  - import_tasks: neovim.yml 

  - import_tasks: tmux.yml 
  
  - import_tasks: fonts.yml
